apiVersion: v1
kind: Pod
metadata:
  name: pi
spec:
  containers:
    - name: pi
      image: quay.io/rhte_2019/pi:latest
      volumeMounts:
      - name: config-volume
        mountPath: /root/.s3cfg
        subPath: .s3cfg
  volumes:
    - name: config-volume
      configMap:
        name: s3cfg
  restartPolicy: Never