apiVersion: v1
kind: ConfigMap
metadata:
  name: s3cfg
data:
  .s3cfg: |-
    [default]
    access_key = {s3_generated_access_key}
    secret_key = {s3_generated_secret_key}
    acl_public = True
    bucket_location = US
    default_mime_type = binary/octet-stream
    delete_removed = False
    dry_run = False
    encoding = UTF-8
    encrypt = False
    force = False
    get_continue = False
    gpg_command = /usr/bin/gpg
    gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
    gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
    gpg_passphrase =
    guess_mime_type = True
    host_base = {s3_host_base}
    host_bucket = {s3_host_bucket}
    human_readable_sizes = False
    list_md5 = False
    preserve_attrs = True
    progress_meter = True
    proxy_host =
    proxy_port = 0
    recursive = False
    recv_chunk = 4096
    send_chunk = 4096
    skip_existing = False
    urlencoding_mode = normal
    use_https = False
    verbosity = WARNING