apiVersion: v1
kind: Template
labels:
  template: pi-calculator
metadata:
  annotations:
    description: |
      Template to deploy pi calculator pod and its related resources.
    openshift.io/provider-display-name: Red Hat Tech Exchange.
    tags: pi,s3
  name: pi-calculator
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: s3cfg
  data:
    .s3cfg: |-
      [default]
      access_key = {S3_ACCESS_KEY}
      secret_key = {S3_SECRET_KEY}
      acl_public = True
      bucket_location = US
      default_mime_type = binary/octet-stream
      delete_removed = False
      dry_run = False
      encoding = UTF-8
      encrypt = False
      force = False
      get_continue = False
      gpg_command = /usr/bin/gpg
      gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
      gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
      gpg_passphrase =
      guess_mime_type = True
      host_base = {S3_HOST_BASE}
      host_bucket = {S3_HOST_BUCKET}
      human_readable_sizes = False
      list_md5 = False
      preserve_attrs = True
      progress_meter = True
      proxy_host =
      proxy_port = 0
      recursive = False
      recv_chunk = 4096
      send_chunk = 4096
      skip_existing = False
      urlencoding_mode = normal
      use_https = False
      verbosity = WARNING

- apiVersion: v1
  kind: Pod
  metadata:
    name: pi
  spec:
    containers:
    - env:
      - name: S3_BUCKET
        value: ${S3_HOST_BUCKET}
      args: ["$(THREADS)", "${DECIMALS}"]
      name: pi
      image: quay.io/rhte_2019/pi:latest
      volumeMounts:
      - name: config-volume
        mountPath: /root/.s3cfg
        subPath: .s3cfg
    volumes:
      - name: config-volume
        configMap:
          name: s3cfg
    restartPolicy: Never

parameters:
- description: S3 Access key
  displayName: Access key
  name: S3_ACCESS_KEY
  required: true
- description: S3 Secret key
  displayName: Secret key
  name: S3_SECRET_KEY
  required: true
- description: S3 Host base
  displayName: Host base
  name: S3_HOST_BASE
  required: true
- description: S3 Host bucket
  displayName: Host bucket
  name: S3_HOST_BUCKET
  required: true
- description: Number of threads to be used to calculate pi
  displayName: Number of Threads
  name: THREADS
  value: 1
- description: Number of decimals to be used to calculate pi
  displayName: Number of decimals
  name: DECIMALS
  value: 10