---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-rgw-keys
type: Opaque
data:
  rgw_user_user_key: Zm9v
  rgw_user_secret_key: YmFy
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-nano
  labels:
    app: ceph
    daemon: nano
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ceph
    daemon: nano
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: ceph-nano
spec:
  to:
    kind: Service
    name: ceph-nano
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-dashboard
  labels:
    app: ceph
    daemon: nano
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ceph
    daemon: nano
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: ceph-dashboard
spec:
  to:
    kind: Service
    name: ceph-dashboard
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: ceph
      daemon: nano
    name: ceph-nano
  spec:
    replicas: 1
    serviceName: ceph-nano
    selector:
      matchLabels:
        app: ceph
    template:
      metadata:
        name: ceph-nano
        labels:
          app: ceph
          daemon: nano
      spec:
        containers:
        - image: ceph/daemon
          imagePullPolicy: Always
          name: ceph-nano
          ports:
          - containerPort: 8000
            name: cn-s3
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
          env:
          - name: NETWORK_AUTO_DETECT
            value: "4"
          - name: RGW_FRONTEND_PORT
            value: "8000"
          - name: RGW_CIVETWEB_PORT
            value: "8000"
          - name: SREE_PORT
            value: "5001"
          - name: CEPH_DEMO_UID
            value: "nano"
          - name: CEPH_DAEMON
            value: "demo"
          - name: DEBUG
            value: "verbose"
          - name: CEPH_DEMO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ceph-rgw-keys
                key: rgw_user_user_key
          - name: CEPH_DEMO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ceph-rgw-keys
                key: rgw_user_secret_key
