---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cn-pv-claim-var
  labels:
    app: ceph
    daemon: nano
spec:
  accessModes:
        - ReadWriteOnce
  resources:
      requests:
        storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cn-pv-claim-etc
  labels:
        app: ceph
        daemon: nano
spec:
  accessModes:
        - ReadWriteOnce
  resources:
        requests:
          storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-rgw-keys
type: Opaque
data:
  rgw_user_user_key: Zm9v
  rgw_user_secret_key: YmFy
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-nano-services
  labels:
    app: ceph
    daemon: nano
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ceph
    daemon: nano
  sessionAffinity: None
  type: ClusterIP
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: ceph
      daemon: nano
    name: ceph-nano
  spec:
    replicas: 1
    serviceName: ceph-nano
    selector:
      matchLabels:
        app: ceph
    template:
      metadata:
        name: ceph-nano
        labels:
          app: ceph
          daemon: nano
      spec:
        containers:
        - image: ceph/daemon
          imagePullPolicy: Always
          name: ceph-nano
          ports:
          - containerPort: 8000
            name: cn-s3
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: "1"
              memory: 512M
          env:
          - name: NETWORK_AUTO_DETECT
            value: "4"
          - name: RGW_FRONTEND_PORT
            value: "8000"
          - name: RGW_CIVETWEB_PORT
            value: "8000"
          - name: SREE_PORT
            value: "5001"
          - name: CEPH_DEMO_UID
            value: "nano"
          - name: CEPH_DAEMON
            value: "demo"
          - name: DEBUG
            value: "verbose"
          - name: CEPH_DEMO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ceph-rgw-keys
                key: rgw_user_user_key
          - name: CEPH_DEMO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ceph-rgw-keys
                key: rgw_user_secret_key
          volumeMounts:
          - name: cn-varlibceph
            mountPath: /var/lib/ceph
          - name: cn-etcceph
            mountPath: /etc/ceph
        volumes:
        - name: cn-varlibceph
          persistentVolumeClaim:
             claimName: cn-pv-claim-var
        - name: cn-etcceph
          persistentVolumeClaim:
            claimName: cn-pv-claim-etc
